### ISSUE TITLE
Docker important note

### ISSUE THREAD

**Issue by pepitooo** [fjgalesloot/roon-extension-mqtt#19]
Don't forget to set the docker container to use host network

here my docker-compose.yaml or stack using portainer
```
version: "2"
services:
  roon-extension-mqtt:
    image: fjgalesloot/roon-extension-mqtt:latest
    container_name: roon-extension-mqtt
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /home/my-username/roon-extension-mqtt/config:/usr/src/app/config/
```
